apiVersion: v1
kind: Service
metadata:
  name: server-admin-pod
  labels:
    name: server-admin-pod
    app: demo-server-admin-pod

spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
      name: server-admin-pod
      app: demo-server-admin-pod
